---
# SSL certificate configuration
ssl_provider: "letsencrypt"
ssl_acme_email: ""
ssl_domains: []
ssl_key_size: 4096
ssl_dhparam_size: 4096

# Let's Encrypt configuration
letsencrypt_staging: false
letsencrypt_directory: "https://acme-v02.api.letsencrypt.org/directory"
letsencrypt_staging_directory: "https://acme-staging-v02.api.letsencrypt.org/directory"
letsencrypt_agree_tos: true
letsencrypt_challenge: "http-01"
letsencrypt_webroot_path: "/var/www/letsencrypt"

# Certificate paths
ssl_cert_path: "/etc/ssl/certs"
ssl_key_path: "/etc/ssl/private"
ssl_dhparam_path: "/etc/ssl/dhparam.pem"

# Certificate renewal
ssl_renewal_enabled: true
ssl_renewal_hour: "3"
ssl_renewal_minute: "30"

# OCSP stapling
ssl_ocsp_stapling: true

# SSL security settings
ssl_protocols: "TLSv1.2 TLSv1.3"
ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
ssl_prefer_server_ciphers: "off"

# HSTS configuration
ssl_hsts_enabled: true
ssl_hsts_max_age: 31536000
ssl_hsts_include_subdomains: true
ssl_hsts_preload: true

# Certificate transparency
ssl_ct_submit_logs: true

# Backup settings
ssl_backup_enabled: true
ssl_backup_path: "/var/backups/ssl"