---
# Global configuration for all servers
timezone: "UTC"
ntp_servers:
  - "0.debian.pool.ntp.org"
  - "1.debian.pool.ntp.org"
  - "2.debian.pool.ntp.org"
  - "3.debian.pool.ntp.org"

# Security settings
ssh_port: 2222
ssh_max_auth_tries: 3
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_login_grace_time: 60

# Fail2Ban settings
fail2ban_enabled: true
fail2ban_bantime: 3600
fail2ban_findtime: 600
fail2ban_maxretry: 5

# Firewall settings
ufw_enabled: true
ufw_default_policy_incoming: deny
ufw_default_policy_outgoing: allow
ufw_default_policy_forward: deny

# Automatic updates
unattended_upgrades_enabled: true
auto_reboot_if_required: true
auto_reboot_time: "03:00"

# Monitoring
monitoring_enabled: true
monitoring_email: "{{ vault_ssl_email }}"
log_retention_days: 30

# System hardening
disable_ipv6: false
kernel_hardening_enabled: true
sysctl_hardening_enabled: true

# Matrix Server Configuration
# These reference secrets from vault.yml
matrix_domain: "chat.example.com"  # Change to your domain
matrix_homeserver_name: "matrix.example.com"  # Change to your Matrix domain
ssl_email: "{{ vault_ssl_email }}"  # From vault

# Admin user configuration (from vault)
admin_username: "{{ vault_admin_username }}"
admin_user_password: "{{ vault_admin_password }}"

# Database passwords (from vault)
matrix_database_password: "{{ vault_matrix_database_password }}"

# Matrix secrets (from vault)
form_secret: "{{ vault_form_secret }}"
macaroon_secret_key: "{{ vault_macaroon_secret_key }}"
registration_secret: "{{ vault_registration_secret }}"
coturn_secret: "{{ vault_coturn_secret }}"