---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart caddy
  systemd:
    name: caddy
    state: restarted

- name: reload caddy
  systemd:
    name: caddy
    state: reloaded

- name: stop caddy
  systemd:
    name: caddy
    state: stopped

- name: start caddy
  systemd:
    name: caddy
    state: started