---
- name: reload ufw
  ufw:
    state: reloaded

- name: restart ufw
  systemd:
    name: ufw
    state: restarted

- name: reload iptables
  command: iptables-restore /etc/iptables/rules.security
  ignore_errors: yes

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted