---
- name: restart ssh
  systemd:
    name: ssh
    state: restarted

- name: restart auditd
  systemd:
    name: auditd
    state: restarted

- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: reload sysctl
  command: sysctl -p