---
# Caddy configuration
caddy_version: "2.7.6"
caddy_user: "caddy"
caddy_group: "caddy"
caddy_config_dir: "/etc/caddy"
caddy_data_dir: "/var/lib/caddy"
caddy_log_dir: "/var/log/caddy"
caddy_binary_path: "/usr/local/bin/caddy"

# Caddyfile configuration
caddy_config_file: "{{ caddy_config_dir }}/Caddyfile"
caddy_auto_https: true
caddy_admin_endpoint: "localhost:2019"

# Matrix configuration for Caddy
matrix_domain: "{{ matrix_domain }}"
matrix_homeserver_name: "{{ matrix_homeserver_name }}"
element_subdomain: ""  # Empty for root domain, or 'chat' for chat.domain.com

# SSL email for Let's Encrypt
caddy_acme_email: "{{ ssl_email }}"

# Security headers
caddy_security_headers:
  X-Frame-Options: "DENY"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"
  Referrer-Policy: "strict-origin-when-cross-origin"
  Permissions-Policy: "geolocation=(), microphone=(), camera=()"

# Rate limiting
caddy_rate_limit_enabled: true
caddy_rate_limit_requests: "100"
caddy_rate_limit_window: "1m"

# Logging
caddy_access_log: "{{ caddy_log_dir }}/access.log"
caddy_error_log: "{{ caddy_log_dir }}/error.log"
caddy_log_level: "INFO"

# Health check endpoint
caddy_health_check_enabled: true
caddy_health_check_path: "/health"

# Admin API security
caddy_admin_api_enabled: false  # Disable by default for security