---
# Matrix Server Inventory - Production
# This file defines your Matrix server(s) and connection details

all:
  children:
    matrix_servers:
      hosts:
        # CHANGE THIS: Replace with your actual server details
        your-matrix-server:
          # Server connection details
          ansible_host: YOUR_SERVER_IP          # Replace with your server IP
          ansible_user: root                    # SSH user (root or sudo user)
          ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Path to your SSH key
          ansible_ssh_port: 22                  # SSH port (22 or custom port like 2222)

          # Matrix configuration - these override the global settings
          matrix_domain: "chat.yourdomain.com"           # Where Element web will be hosted
          matrix_homeserver_name: "matrix.yourdomain.com" # Your Matrix homeserver domain

          # Optional: Server-specific overrides
          # postgresql_max_connections: 200
          # matrix_max_upload_size: "100M"

      vars:
        # Global Matrix server settings
        ansible_python_interpreter: /usr/bin/python3
        ansible_become: yes
        ansible_become_method: sudo

        # Connection settings
        ansible_ssh_pipelining: true
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

        # Deployment settings
        gather_facts: yes
        fact_caching: memory
        host_key_checking: false

# Example configurations for different deployment scenarios:

# SCENARIO 1: Local deployment (running Ansible on the target server)
# Uncomment and modify this if you're running the deployment ON the Matrix server:
#
# matrix_servers:
#   hosts:
#     localhost:
#       ansible_connection: local
#       ansible_python_interpreter: /usr/bin/python3
#       matrix_domain: "chat.yourdomain.com"
#       matrix_homeserver_name: "matrix.yourdomain.com"

# SCENARIO 2: Remote deployment with custom SSH port
# Uncomment and modify if your server uses a custom SSH port:
#
# matrix_servers:
#   hosts:
#     your-matrix-server:
#       ansible_host: YOUR_SERVER_IP
#       ansible_user: your_sudo_user
#       ansible_ssh_port: 2222
#       ansible_ssh_private_key_file: ~/.ssh/your_key
#       become_user: root

# SCENARIO 3: Multiple Matrix servers (advanced)
# Uncomment for multiple server deployment:
#
# matrix_servers:
#   hosts:
#     matrix1.yourdomain.com:
#       ansible_host: IP1
#       matrix_domain: "chat1.yourdomain.com"
#       matrix_homeserver_name: "matrix1.yourdomain.com"
#     matrix2.yourdomain.com:
#       ansible_host: IP2
#       matrix_domain: "chat2.yourdomain.com"
#       matrix_homeserver_name: "matrix2.yourdomain.com"