---
# Matrix server specific configuration
matrix_synapse_version: "latest"
matrix_synapse_database: postgresql
matrix_element_enabled: true
matrix_coturn_enabled: true

# PostgreSQL settings
postgresql_version: "15"
postgresql_max_connections: 100
postgresql_shared_buffers: "256MB"
postgresql_effective_cache_size: "1GB"
postgresql_maintenance_work_mem: "64MB"
postgresql_work_mem: "4MB"

# SSL/TLS settings
ssl_provider: "letsencrypt"
ssl_acme_email: "{{ ssl_email }}"
ssl_key_size: 4096
ssl_dhparam_size: 4096

# Nginx settings
nginx_worker_processes: auto
nginx_worker_connections: 1024
nginx_client_max_body_size: "50M"

# Coturn settings (for VoIP)
coturn_realm: "{{ matrix_domain }}"
coturn_external_ip: "{{ ansible_default_ipv4.address }}"
coturn_min_port: 49152
coturn_max_port: 65535

# Matrix settings
matrix_max_upload_size: "50M"
matrix_registration_enabled: false
matrix_guest_access_enabled: false
matrix_federation_enabled: true
matrix_presence_enabled: true
matrix_typing_enabled: true
matrix_receipts_enabled: true

# Backup settings
backup_enabled: true
backup_retention_days: 7
backup_schedule: "0 2 * * *"  # Daily at 2 AM

# Rate limiting
rate_limiting_enabled: true
rate_limit_per_second: 10
rate_limit_burst: 50

# Log levels
matrix_log_level: "INFO"
nginx_log_level: "warn"