---
- name: Install required packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - build-essential
      - libffi-dev
      - libjpeg-dev
      - libpq-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - postgresql
      - postgresql-contrib
      - redis-server
      - certbot
      - coturn
    state: present
    update_cache: yes

- name: Create matrix user and group
  group:
    name: "{{ matrix_synapse_group }}"
    state: present

- name: Create matrix user
  user:
    name: "{{ matrix_synapse_user }}"
    group: "{{ matrix_synapse_group }}"
    system: yes
    shell: /bin/false
    home: "{{ matrix_synapse_home }}"
    createhome: yes

- name: Create matrix directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ matrix_synapse_user }}"
    group: "{{ matrix_synapse_group }}"
    mode: '0750'
  loop:
    - "{{ matrix_synapse_home }}"
    - "{{ matrix_synapse_config_dir }}"
    - "{{ matrix_synapse_data_dir }}"
    - "{{ matrix_synapse_log_dir }}"
    - "{{ matrix_uploads_path }}"
    - "{{ matrix_media_store_path }}"

- name: Set up PostgreSQL
  include_tasks: postgresql.yml

- name: Configure Redis
  include_tasks: redis.yml
  ignore_errors: yes

- name: Install Matrix Synapse
  include_tasks: synapse.yml
  ignore_errors: yes

- name: Configure Coturn
  include_tasks: coturn.yml
  when: matrix_coturn_enabled | default(false)
  ignore_errors: yes

- name: Install and configure Element
  include_tasks: element.yml
  when: matrix_element_enabled | default(false)
  ignore_errors: yes


- name: Configure SSL certificates
  include_tasks: ssl.yml
  ignore_errors: yes

- name: Configure monitoring
  include_tasks: monitoring.yml
  ignore_errors: yes

- name: Configure backups
  include_tasks: backup.yml
  when: matrix_backup_enabled | default(false)
  ignore_errors: yes

- name: Configure fail2ban for Matrix
  include_tasks: fail2ban.yml
  ignore_errors: yes

- name: Create Matrix admin user script
  template:
    src: create-admin-user.sh.j2
    dest: /usr/local/bin/create-matrix-admin.sh
    owner: root
    group: root
    mode: '0755'

- name: Display setup information
  debug:
    msg: |
      Matrix server setup completed!

      Matrix domain: {{ matrix_domain }}
      Homeserver: {{ matrix_homeserver_name }}
      Element URL: https://{{ matrix_domain }}
      Admin panel: https://{{ matrix_homeserver_name }}/_synapse/admin/

      To create an admin user, run:
      /usr/local/bin/create-matrix-admin.sh username password

      Make sure to:
      1. Configure DNS for {{ matrix_domain }} and {{ matrix_homeserver_name }}
      2. Set up proper SSL certificates
      3. Configure your firewall rules
      4. Test federation with: https://federationtester.matrix.org/