---
# SSH hardening defaults
ssh_port: 2222
ssh_protocol: 2
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_pubkey_authentication: "yes"
ssh_challenge_response_authentication: "no"
ssh_gss_api_authentication: "no"
ssh_host_based_authentication: "no"
ssh_permit_empty_passwords: "no"
ssh_permit_user_environment: "no"
ssh_use_pam: "yes"
ssh_x11_forwarding: "no"
ssh_print_motd: "no"
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_max_auth_tries: 3
ssh_max_sessions: 2
ssh_tcp_forwarding: "no"
ssh_agent_forwarding: "no"
ssh_gateway_ports: "no"
ssh_permit_tunnel: "no"
ssh_compression: "no"

# Kernel hardening
kernel_hardening:
  # Network security
  net.ipv4.ip_forward: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.default.send_redirects: 0
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv4.conf.all.secure_redirects: 0
  net.ipv4.conf.default.secure_redirects: 0
  net.ipv6.conf.all.accept_redirects: 0
  net.ipv6.conf.default.accept_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.default.accept_source_route: 0
  net.ipv6.conf.all.accept_source_route: 0
  net.ipv6.conf.default.accept_source_route: 0
  net.ipv4.conf.all.log_martians: 1
  net.ipv4.icmp_echo_ignore_broadcasts: 1
  net.ipv4.icmp_ignore_bogus_error_responses: 1
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1
  net.ipv4.tcp_syncookies: 1

  # Memory protection
  kernel.dmesg_restrict: 1
  kernel.kptr_restrict: 2
  kernel.yama.ptrace_scope: 1
  kernel.kexec_load_disabled: 1

  # File system hardening
  fs.protected_hardlinks: 1
  fs.protected_symlinks: 1
  fs.suid_dumpable: 0

# Package hardening
remove_packages:
  - telnet
  - rsh-client
  - rsh-redone-client
  - talk
  - ntalk
  - ypbind
  - nis
  - tftp
  - xinetd
  - openbsd-inetd

# User account settings
password_max_age: 90
password_min_age: 7
password_warn_age: 14
login_retries: 3
login_timeout: 60

# File permissions
secure_directories:
  - path: /etc/ssh
    mode: "0755"
  - path: /etc/ssl/private
    mode: "0700"
  - path: /var/log
    mode: "0755"

secure_files:
  - path: /etc/passwd
    mode: "0644"
  - path: /etc/shadow
    mode: "0640"
  - path: /etc/group
    mode: "0644"
  - path: /etc/gshadow
    mode: "0640"

# Service hardening
disable_services:
  - avahi-daemon
  - cups
  - nfs-common
  - rpcbind
  - rsync
  - xinetd

# Audit settings
auditd_enabled: true
audit_rules:
  - "-w /etc/passwd -p wa -k identity"
  - "-w /etc/group -p wa -k identity"
  - "-w /etc/shadow -p wa -k identity"
  - "-w /etc/gshadow -p wa -k identity"
  - "-w /etc/sudoers -p wa -k actions"
  - "-w /var/log/faillog -p wa -k logins"
  - "-w /var/log/lastlog -p wa -k logins"