---
- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted
    daemon_reload: yes
  listen: restart postgresql

- name: reload postgresql
  systemd:
    name: postgresql
    state: reloaded
  listen: reload postgresql

- name: restart matrix-synapse
  systemd:
    name: matrix-synapse
    state: restarted
    daemon_reload: yes
  listen: restart matrix-synapse

- name: reload matrix-synapse
  systemd:
    name: matrix-synapse
    state: reloaded
  listen: reload matrix-synapse

- name: restart redis
  systemd:
    name: redis-server
    state: restarted
  listen: restart redis

- name: restart coturn
  systemd:
    name: coturn
    state: restarted
  listen: restart coturn