---
galaxy_info:
  author: Server Admin
  description: User management and SSH hardening for zerokaine user
  company:
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 12
  galaxy_tags:
    - users
    - ssh
    - security
dependencies: []