---
galaxy_info:
  author: Server Admin
  description: UFW firewall configuration with security rules
  company:
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 12
  galaxy_tags:
    - security
    - firewall
    - ufw
dependencies: []