---
all:
  children:
    matrix_servers:
      hosts:
        matrix-staging.example.com:
          ansible_host: 192.168.1.101
          ansible_user: debian
          ansible_ssh_private_key_file: ~/.ssh/matrix_staging_ed25519
          ansible_ssh_port: 2222
          matrix_domain: staging.example.com
          matrix_homeserver_name: matrix-staging.example.com
          ssl_email: admin@example.com
      vars:
        ansible_python_interpreter: /usr/bin/python3
        become: yes
        become_method: sudo