---
galaxy_info:
  author: Server Admin
  description: Comprehensive Debian 12 server hardening
  company:
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 12
  galaxy_tags:
    - security
    - hardening
    - debian
dependencies: []