---
- name: Server hardening playbook
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: user_management
      tags: ['users', 'ssh', 'security']

    - role: debian_hardening
      tags: ['hardening', 'security', 'ssh', 'kernel']

    - role: firewall
      tags: ['firewall', 'ufw', 'iptables']

  tasks:
    - name: Run security audit with Lynis
      command: lynis audit system --quiet --no-colors
      register: lynis_output
      changed_when: false
      failed_when: false
      tags: ['audit']

    - name: Save Lynis report
      copy:
        content: "{{ lynis_output.stdout }}"
        dest: "/var/log/lynis-{{ ansible_date_time.epoch }}.log"
        owner: root
        group: root
        mode: '0600'
      when: lynis_output.stdout is defined
      tags: ['audit']

    - name: Run rootkit check
      command: "{{ item }}"
      register: security_check
      changed_when: false
      failed_when: false
      loop:
        - "rkhunter --check --sk"
        - "chkrootkit"
      tags: ['rootkit']

    - name: Display hardening summary
      debug:
        msg: |
          ================================
          SERVER HARDENING COMPLETE
          ================================

          ✅ System packages updated
          ✅ SSH hardened (port {{ ssh_port }})
          ✅ Firewall configured
          ✅ Kernel parameters hardened
          ✅ File permissions secured
          ✅ Audit logging enabled
          ✅ Automatic updates configured
          ✅ Security tools installed

          📋 Security Tools Installed:
          - fail2ban (intrusion prevention)
          - ufw (firewall)
          - auditd (system auditing)
          - rkhunter (rootkit detection)
          - chkrootkit (rootkit scanner)
          - aide (file integrity)
          - lynis (security auditing)

          📁 Important Files:
          - SSH config: /etc/ssh/sshd_config
          - Firewall rules: /etc/ufw/
          - Audit logs: /var/log/audit/
          - Security logs: /var/log/security/

          ⚠️  Important Notes:
          - SSH now runs on port {{ ssh_port }}
          - Root login disabled
          - Password authentication disabled
          - Only key-based authentication allowed

          🔧 Next Steps:
          - Review Lynis report: /var/log/lynis-{{ ansible_date_time.epoch }}.log
          - Configure log monitoring
          - Set up automated security updates
          - Schedule regular security scans
      tags: ['summary']